#!/usr/bin/env bash
set -uo pipefail   # NOT -e: we deliberately drive the failure branch
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/../scripts/program-lib.sh"
fail=0
TEST_TMPDIR=$(mktemp -d)
trap 'rm -rf "$TEST_TMPDIR"' EXIT

SKILL="link-health-scanner"
FAKE_SHA="85449beabc1234567890abcdef1234567890abcd"

# =============================================================================
# Branch 1: gh succeeds -> _meta.json is written and the @<sha> footer emitted.
# =============================================================================
dir1="$TEST_TMPDIR/case1"
mkdir -p "$dir1"
CALLS1="$TEST_TMPDIR/calls1"; echo 0 > "$CALLS1"
gh() {
  local n; n=$(cat "$CALLS1"); echo $((n+1)) > "$CALLS1"
  printf '%s\n' "$FAKE_SHA"
}

sha=$(SKILL_SOURCE_REPO="rossoctl/agent-skills" resolve_skill_meta "$dir1" "$SKILL")
[ "$sha" = "$FAKE_SHA" ] \
  || { echo "FAIL branch1: resolve_skill_meta should echo resolved SHA, got [$sha]"; fail=1; }
[ -f "$dir1/_meta.json" ] \
  || { echo "FAIL branch1: _meta.json should be written on success"; fail=1; }
if [ -f "$dir1/_meta.json" ]; then
  v=$(jq -r '.version' "$dir1/_meta.json")
  s=$(jq -r '.source' "$dir1/_meta.json")
  [ "$v" = "$FAKE_SHA" ] || { echo "FAIL branch1: _meta.json .version wrong: [$v]"; fail=1; }
  [ "$s" = "rossoctl/agent-skills" ] || { echo "FAIL branch1: _meta.json .source wrong: [$s]"; fail=1; }
  jq -e 'has("installed_at")' "$dir1/_meta.json" >/dev/null \
    || { echo "FAIL branch1: _meta.json missing installed_at"; fail=1; }
fi
# skill_attribution emits the pinned-SHA footer with the blob/<sha> link.
foot=$(SCRIPT_DIR="$dir1" SKILL_SOURCE_REPO="rossoctl/agent-skills" skill_attribution "$SKILL")
case "$foot" in
  *"Generated by RepoMan $SKILL@${FAKE_SHA:0:7}"*"blob/$FAKE_SHA/skills/$SKILL/SKILL.md"*) ;;
  *) echo "FAIL branch1: attribution footer wrong: [$foot]"; fail=1 ;;
esac

# =============================================================================
# Branch 2: gh fails -> nothing is written and the blob/main fallback emitted.
# =============================================================================
dir2="$TEST_TMPDIR/case2"
mkdir -p "$dir2"
gh() { echo "HTTP 403: rate limit exceeded" >&2; return 1; }

sha=$(SKILL_SOURCE_REPO="rossoctl/agent-skills" resolve_skill_meta "$dir2" "$SKILL" 2>/dev/null)
[ -z "$sha" ] \
  || { echo "FAIL branch2: resolve_skill_meta should echo empty on gh failure, got [$sha]"; fail=1; }
[ ! -f "$dir2/_meta.json" ] \
  || { echo "FAIL branch2: _meta.json must NOT be written on failure (self-heal retry)"; fail=1; }
foot=$(SCRIPT_DIR="$dir2" SKILL_SOURCE_REPO="rossoctl/agent-skills" skill_attribution "$SKILL" 2>/dev/null)
case "$foot" in
  *"blob/main/skills/$SKILL/SKILL.md"*) ;;
  *) echo "FAIL branch2: fallback footer should use blob/main, got: [$foot]"; fail=1 ;;
esac
case "$foot" in
  *"@"*) echo "FAIL branch2: fallback footer must NOT carry an @<sha>, got: [$foot]"; fail=1 ;;
esac

# =============================================================================
# Branch 3: pre-existing _meta.json is read, never overwritten, no gh call.
# =============================================================================
dir3="$TEST_TMPDIR/case3"
mkdir -p "$dir3"
PINNED="deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
printf '{"version":"%s","source":"rossoctl/agent-skills","installed_at":"2026-01-01"}\n' \
  "$PINNED" > "$dir3/_meta.json"
GH_CALLED="$TEST_TMPDIR/gh_called"; : > "$GH_CALLED"
gh() { echo called >> "$GH_CALLED"; printf '%s\n' "$FAKE_SHA"; }

sha=$(SKILL_SOURCE_REPO="rossoctl/agent-skills" resolve_skill_meta "$dir3" "$SKILL")
[ "$sha" = "$PINNED" ] \
  || { echo "FAIL branch3: should echo the pre-existing pinned SHA, got [$sha]"; fail=1; }
[ ! -s "$GH_CALLED" ] \
  || { echo "FAIL branch3: gh must NOT be called when _meta.json exists"; fail=1; }
v=$(jq -r '.version' "$dir3/_meta.json")
[ "$v" = "$PINNED" ] \
  || { echo "FAIL branch3: existing _meta.json must not be overwritten, got [$v]"; fail=1; }

unset -f gh
[ "$fail" -eq 0 ] && echo "PASS: skill-meta provenance+attribution" || exit 1
